[package]
name = "demo-russimp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
wme-core = { path = "../wme-core/"}
glfw = "0.58.0"
gl = "0.14.0"
nalgebra-glm = "0.19.0"
tobj = "4.0.2"
